author: Drafintech <info@drafintech.it>
description: The simple polymer datepicker you were missing
version: 0.2.0
name: polymer_datepicker
homepage: https://github.com/dam0vm3nt/polymer_datepicker
dependencies:
    intl: '>=0.12.4 <0.13.0'
    polymer: any
    web_components: '>=0.12.0'
    observe: any
    polymer_autonotify:
     path: ../polymer_autonotify
#    browser: any
    polymer_elements:
     git:
      ref: master
      url: https://github.com/dart-lang/polymer_elements.git

dependency_overrides:
  polymer:
    git:
      ref: behaviors
      url: https://github.com/dart-lang/polymer-dart.git
  polymer_autonotify:
   path: ../polymer_autonotify
  polymer_interop:
    git:
      ref: 0.2.0-dev
      url: https://github.com/dart-lang/polymer_interop.git

transformers:
- polymer_autonotify
- observe
