author: "Drafintech <info@drafintech.it>"
description: "The simple polymer datepicker you were missing"
homepage: "https://github.com/dam0vm3nt/polymer_datepicker"
name: "polymer_datepicker"
version: "0.9.0"
dependencies: 
  autonotify_observe: "^1.0.0"
  intl: ">=0.12.4 <0.13.0"
  polymer_elements: "^1.0.0-rc.5"
environment: 
  sdk: ">=1.8.0 <2.0.0"
transformers: 
  - "autonotify_observe"
