author: Drafintech <info@drafintech.it>
description: The simple polymer datepicker you were missing
version: 0.1.5
name: polymer_datepicker
homepage: http://www.drafintech.it
dependencies:
    intl: '>=0.12.4 <0.13.0'
    core_elements: '>=0.7.1+2 <0.8.0'
    polymer: '>=0.16.3+3 <0.17.0'
#    browser: any
    paper_elements: '>=0.7.1+1 <0.8.0'
transformers:
- polymer
