author: Drafintech <info@drafintech.it>
description: The simple polymer datepicker you were missing
version: 0.1.2
name: polymer_datepicker
homepage: http://www.drafintech.it
dependencies:
    intl: any
    core_elements: any
    polymer: any
    browser: any
    paper_elements: any
transformers:
- polymer
