name: demo_polymer_datepicker
description: Demo project for polymer datepicker
version: 0.0.1
author: Vittorio Ballestra <vittorio.ballestra@drafintech.it>
homepage: https://github.com/dam0vm3nt/polymer_autonotify
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
 polymer_elements: "^1.0.0-rc.5"
 web_components: '^0.12.0'
 autonotify_observe: '^1.0.0'
 polymer_datepicker:
  path: ..
 intl: any

#dependency_overrides:
# autonotify_observe:
#   path: ../../autonotify_observe

transformers:
- autonotify_observe:
    entry_points:
    - web/index.html
