name: demo_polymer_datepicker
description: Demo project for polymer datepicker
version: 0.0.1
author: Vittorio Ballestra <vittorio.ballestra@drafintech.it>
homepage: https://github.com/dam0vm3nt/polymer_autonotify
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  polymer: "^1.0.0-rc.15"
  polymer_datepicker:
    path: ..

transformers:
- polymer:
    entry_points:
    - web/index.html
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: false
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
